apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-dashboard
  namespace: {{ .Release.Namespace }}
spec:
  commonName: longhorn.lab.krancovia.io
  dnsNames:
  - longhorn.lab.krancovia.io
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-gandi
  secretName: longhorn-tls
