apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-gandi-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: kent.rancourt@gmail.com
    privateKeySecretRef:
      name: letsencrypt-gandi-staging
    solvers:
    - dns01:
        webhook:
          groupName: acme.bwolf.me
          solverName: gandi
          config:
            apiKeySecretRef:
              name: gandi-credentials
              key: api-token
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-gandi
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: kent.rancourt@gmail.com
    privateKeySecretRef:
      name: letsencrypt-gandi
    solvers:
    - dns01:
        webhook:
          groupName: acme.bwolf.me
          solverName: gandi
          config:
            apiKeySecretRef:
              name: gandi-credentials
              key: api-token
