apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gandi-credentials
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBmEjwwORYEWN5wJsJvO5JAg15UZCfs7b844bBnfucimpYovXDnNkYFcM5zHxLO0qjMvDOyjdfnbbyu6I34G55vwXnpQIbdcQOPoER4irMok+tS1dxQQqP06H1rKJiJSWvhoGOH/7dmPJ0TzH2aImg03qnds6tM0vbMYSgsh2efvELt5rO+iJ6aQrG6SBOXbAXSaDw0o7dwdaQy6ZUDFhRosvVPcxuReIvJQ+IYso/RfbGqRyaXCXbDCAH95WQwTR1WvsBSkr5NaEEgdy0787/+4mCjSsj6amJt4/vRPC+aKI7I0Tf6V9qNrWaZ35P1gjquSP6LlGXbDFyn1b3am9NGCzsv41IWDLu6UNlecMguZcxSUuv2k7il4wO9S/Yl2hTF9lWOiyvKUWHKsVlPMpmnlA0YngzTRIBLOIHy0aeTFu1hpe55BY9XC5Pa9bdKdnOxCfTdJjza5xxODT94T0ObzOb5C2RrxctTbOGJaDMcnpTGctr8y7Kpy4NQpuMLBB2KdxGIlxVlDDon6sY36zpjac2uEyXcrEuBAd4biyQCA2qNX5xzQo3G51cDtPHaBJnZN7YkMVgEO3emD0XLVU8XsCsUtyz2rHqDX1XpXDAvL0VfILOuBVrsB4CJBciRViyShg4WYa2lAynRMWD4Y9xKDg+rWPOlpjnGnpvwhHYCWx3ZtluVeDJww2Gx3KIKvziExuAXnTOI8zsVWfMkWb3UqHK7rD5m9WsmdG37pQA7es2UmaZVjk0q
  template:
    metadata:
      name: gandi-credentials
      namespace: cert-manager
    type: Opaque
