apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-client-secret
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    GF_AUTH_GITHUB_CLIENT_SECRET: AgAzWTjm8kaNj1j5yAZx0vujvb9sw2bYGLwHY3+glmpCjkonUKdr/3RiVG5uRtvOn0mCSdnCrzQ2NVMAX8OuF3H5qUUNw1QVGCoSOet8uNwqsD+T+UKlbKoMeVKud+6rr3El3XW+dAtT7kErr9O71Cpng6xYD3NNB3JHUUjt5HJGOe+vnF10kvF0ujOUBaOsqgeQfLEwPy9yTO193x3FYQXsz06MRrcudG4fcaN5WvvJxFahJwN9ON3USfLArElz47WyDp3o8LeQoWQCOO/UZxFbO5oRFvL0OONP4ZYD0Ipk+ybZ0Aob3TVUs+Py5KG+YWhH+GT1rYGd8eIGcCM2WaA64adi7VEjN2bp7moA5db6DYkptdCDF0NyOKcotEBjU/jvlCRnjBfhycuKnLCajQBFW9n2LPoB8T6pDax9V3rJIYiWCR0zIk3RFAwubNz9i4YVwnDfaieReeh6gFNbd6erNonUkmBfDWH/8ENZAMtoTD655kWWl1cvxI4GLzyCpkFg7qEgm2Gsw3C8upjh76Acz6qdaSW4OsQMb60xWssxHc0DqqaPhjCaUPOoROR2gOWuAEmoCE2M7n4bX+/KcTY4ZwoBC72gsuoKwFKTAS2rDkmHKWFI+4s+jxODy2IlpH6aeUyZSCLOZf74rqSi53C995csByA+lCcJ60mVn8MOXq1rjP2wCo7hSd/3ohdT27mGrcPN5LQvTyhB/X6etXs48N3EUwrts3eo6nVVduKhruPRi0rietmb
  template:
    metadata:
      name: github-client-secret
      namespace: {{ .Release.Namespace }}
    type: Opaque
