apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 7.6.1
    helm:
      valueFiles:
      - $values/argocd/values.yaml
  - repoURL: https://github.com/krancovia/lab-gitops.git
    path: argocd/manifests
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
