apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-webhook-gandi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://bwolf.github.io/cert-manager-webhook-gandi
    chart: cert-manager-webhook-gandi
    targetRevision: 0.2.0
    helm:
      values: |
        image:
          repository: krancour/cert-manager-webhook-gandi
          tag: v0.3.0
        logLevel: 2
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
